version: '3'
services:
  backend:
    build: ./backend
    container_name: notas-app-backend
    env_file: 
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: notas-app-frontend
    env_file: 
      - ./frontend/.env
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge


